name: CI - Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: keithmorganibm/apollotest
        tags: latest
        tag_with_sha: true  
  update_IBM_satellite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check where I am
        run: |
          pwd
      - name: Show my files
        run: |
          ls -al
      - uses: IBM/satellite-config-upload-action@v1alpha4
        with:
          satelliteHost: https://api.razee.test.cloud.ibm.com/graphql
          tokenHost: https://iam.test.cloud.ibm.com/identity/token
          apikey: ${{ secrets.IBM_STAGE_APIKEY }}
          filename: './satellite.yml'
          channelUuid: '2fce82e3-bb49-418b-b308-38389aa2db03'
          versionName: 'fromGithub'
